/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.calculadora2;

/**
 *
 * @author ASUS TUF
 */
public class calculadora extends javax.swing.JFrame {

    public float num1;
    public float num2; 
    public String ans; 
    public String operador;
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        texto1 = new javax.swing.JLabel();
        C = new javax.swing.JButton();
        DIV = new javax.swing.JButton();
        MULT = new javax.swing.JButton();
        BOT2 = new javax.swing.JButton();
        BOT1 = new javax.swing.JButton();
        BOT3 = new javax.swing.JButton();
        BOT4 = new javax.swing.JButton();
        BOT6 = new javax.swing.JButton();
        BOT5 = new javax.swing.JButton();
        BOT8 = new javax.swing.JButton();
        SEN = new javax.swing.JButton();
        BOT7 = new javax.swing.JButton();
        RESTA = new javax.swing.JButton();
        BOT9 = new javax.swing.JButton();
        SUMA = new javax.swing.JButton();
        IGUAL = new javax.swing.JButton();
        BOT0 = new javax.swing.JButton();
        PUNTO = new javax.swing.JButton();
        COS = new javax.swing.JButton();
        TAN = new javax.swing.JButton();
        RAIZ = new javax.swing.JButton();
        POTENCIA = new javax.swing.JButton();
        IVA = new javax.swing.JButton();
        ANS = new javax.swing.JButton();

        jButton6.setText("jButton1");

        jButton11.setText("jButton1");

        jButton17.setText("jButton1");

        jButton26.setText("jButton13");

        jButton28.setText("jButton13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        texto1.setOpaque(true);

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        DIV.setText("/");
        DIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIVActionPerformed(evt);
            }
        });

        MULT.setText("*");
        MULT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULTActionPerformed(evt);
            }
        });

        BOT2.setText("2");
        BOT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT2ActionPerformed(evt);
            }
        });

        BOT1.setText("1");
        BOT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT1ActionPerformed(evt);
            }
        });

        BOT3.setText("3");
        BOT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT3ActionPerformed(evt);
            }
        });

        BOT4.setText("4");
        BOT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT4ActionPerformed(evt);
            }
        });

        BOT6.setText("6");
        BOT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT6ActionPerformed(evt);
            }
        });

        BOT5.setText("5");
        BOT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT5ActionPerformed(evt);
            }
        });

        BOT8.setText("8");
        BOT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT8ActionPerformed(evt);
            }
        });

        SEN.setText("SEN");
        SEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SENActionPerformed(evt);
            }
        });

        BOT7.setText("7");
        BOT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT7ActionPerformed(evt);
            }
        });

        RESTA.setText("-");
        RESTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESTAActionPerformed(evt);
            }
        });

        BOT9.setText("9");
        BOT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT9ActionPerformed(evt);
            }
        });

        SUMA.setText("+");
        SUMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUMAActionPerformed(evt);
            }
        });

        IGUAL.setText("=");
        IGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGUALActionPerformed(evt);
            }
        });

        BOT0.setText("0");
        BOT0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOT0ActionPerformed(evt);
            }
        });

        PUNTO.setText(".");
        PUNTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUNTOActionPerformed(evt);
            }
        });

        COS.setText("COS");
        COS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COSActionPerformed(evt);
            }
        });

        TAN.setText("TAN");
        TAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TANActionPerformed(evt);
            }
        });

        RAIZ.setText("RAIZ");
        RAIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAIZActionPerformed(evt);
            }
        });

        POTENCIA.setText("POTENCIA");
        POTENCIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POTENCIAActionPerformed(evt);
            }
        });

        IVA.setText("IVA");
        IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IVAActionPerformed(evt);
            }
        });

        ANS.setText("ANS");
        ANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOT0, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BOT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BOT7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(DIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(MULT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(RESTA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(SEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BOT4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BOT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BOT5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BOT8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BOT3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SUMA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(COS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TAN, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BOT9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BOT6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(IGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(PUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ANS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RAIZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(POTENCIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(texto1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MULT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RESTA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(SEN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BOT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOT3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BOT4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOT5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOT6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BOT7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOT8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BOT9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(SUMA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(IGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BOT0, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(COS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TAN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RAIZ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(POTENCIA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IVA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOT0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT0ActionPerformed
    this.texto1.setText(texto1.getText()+"0");
    }//GEN-LAST:event_BOT0ActionPerformed

    private void BOT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT9ActionPerformed
       this.texto1.setText(texto1.getText()+"9");
    }//GEN-LAST:event_BOT9ActionPerformed

    private void BOT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT8ActionPerformed
        this.texto1.setText(texto1.getText()+"8");
    }//GEN-LAST:event_BOT8ActionPerformed

    private void BOT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT7ActionPerformed
        this.texto1.setText(texto1.getText()+"7");
    }//GEN-LAST:event_BOT7ActionPerformed

    private void BOT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT6ActionPerformed
        this.texto1.setText(texto1.getText()+"6");
    }//GEN-LAST:event_BOT6ActionPerformed

    private void BOT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT5ActionPerformed
        this.texto1.setText(texto1.getText()+"5");
    }//GEN-LAST:event_BOT5ActionPerformed

    private void BOT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT4ActionPerformed
        this.texto1.setText(texto1.getText()+"4");
    }//GEN-LAST:event_BOT4ActionPerformed

    private void BOT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT3ActionPerformed
        this.texto1.setText(texto1.getText()+"3");
    }//GEN-LAST:event_BOT3ActionPerformed

    private void BOT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT2ActionPerformed
        this.texto1.setText(texto1.getText()+"2");
    }//GEN-LAST:event_BOT2ActionPerformed

    private void BOT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOT1ActionPerformed
       this.texto1.setText(texto1.getText()+"1");
    }//GEN-LAST:event_BOT1ActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        texto1.setText("");
    }//GEN-LAST:event_CActionPerformed

    private void SUMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUMAActionPerformed
        this.num1=Float.parseFloat(texto1.getText());
        this.operador = ("+");
        texto1.setText("");
        
    }//GEN-LAST:event_SUMAActionPerformed

    private void IGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGUALActionPerformed
       num2= Float.parseFloat(texto1.getText());
       
       switch(this.operador){
           case "+" : 
           this.texto1.setText(nocero(num1+num2));
           ans= this.texto1.getText();
           break;
        case"-":
            this.texto1.setText(nocero(num1-num2));
            ans=this.texto1.getText();
            break;
            case "*" : 
           this.texto1.setText(nocero(num1*num2));
           ans= this.texto1.getText();
           break;
            case "/" : 
            if(this.num2==0){
                texto1.setText("ERROR MATEMATICO");
            }
            else{
           this.texto1.setText(nocero(num1/num2));
           ans= this.texto1.getText();
            }
           break;
            
            case "raiz" : 
             if(num1<0 && num2%2==0){
                texto1.setText("ERROR MATEMATICO");
            }
             else{
           this.texto1.setText(nocero((float) Math.pow(num1,1/num2)));
           ans= this.texto1.getText();
             }
           break;
             case "potencia" : 
           this.texto1.setText(nocero((float) Math.pow(num1,num2)));
           ans= this.texto1.getText();
           break;
             case "iva":
           this.texto1.setText(nocero(num1+num1*num2/100));
           ans= this.texto1.getText();
           break;
            
    }
    }//GEN-LAST:event_IGUALActionPerformed

    private void ANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANSActionPerformed
       texto1.setText(ans);
    }//GEN-LAST:event_ANSActionPerformed

    private void RESTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESTAActionPerformed
         if("".equals(texto1.getText())){
             texto1.setText("-");
         }
         else{
        this.num1=Float.parseFloat(texto1.getText());
        this.operador = ("-");
        texto1.setText("");
         }
    }//GEN-LAST:event_RESTAActionPerformed

    private void PUNTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUNTOActionPerformed
       if(!texto1.getText().contains(".")){
           texto1.setText(texto1.getText()+".");
       }
    }//GEN-LAST:event_PUNTOActionPerformed

    private void MULTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULTActionPerformed
        this.num1=Float.parseFloat(texto1.getText());
        this.operador = ("*");
        texto1.setText("");
    }//GEN-LAST:event_MULTActionPerformed

    private void DIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIVActionPerformed
        this.num1=Float.parseFloat(texto1.getText());
        this.operador = ("/");
        texto1.setText("");
    }//GEN-LAST:event_DIVActionPerformed

    private void SENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SENActionPerformed
        num1=Float.parseFloat(texto1.getText());
        texto1.setText(Float.toString((float) Math.sin(Math.toRadians(num1))));
        ans= texto1.getText();
    }//GEN-LAST:event_SENActionPerformed

    private void COSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COSActionPerformed
        num1=Float.parseFloat(texto1.getText());
        texto1.setText(Float.toString((float) Math.cos(num1)));
        ans= texto1.getText();
    }//GEN-LAST:event_COSActionPerformed

    private void TANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TANActionPerformed
         num1=Float.parseFloat(texto1.getText());
        texto1.setText(Float.toString((float) Math.tan(num1)));
        ans= texto1.getText();
    }//GEN-LAST:event_TANActionPerformed

    private void RAIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAIZActionPerformed
        this.num1=Float.parseFloat(texto1.getText());
        this.operador = ("raiz");
        texto1.setText("");
    }//GEN-LAST:event_RAIZActionPerformed

    private void POTENCIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POTENCIAActionPerformed
         this.num1=Float.parseFloat(texto1.getText());
        this.operador = ("potencia");
        texto1.setText("");
    }//GEN-LAST:event_POTENCIAActionPerformed

    private void IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IVAActionPerformed
       this.num1=Float.parseFloat(texto1.getText());
       this.operador=("iva");
       texto1.setText("");
    }//GEN-LAST:event_IVAActionPerformed

    public String nocero(float resultado){
        String retorno= ""; 
    retorno=Float.toString(resultado);
    
    if(resultado%1==0){
        retorno= retorno.substring(0, retorno.length()-2);
    }
        return retorno;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANS;
    private javax.swing.JButton BOT0;
    private javax.swing.JButton BOT1;
    private javax.swing.JButton BOT2;
    private javax.swing.JButton BOT3;
    private javax.swing.JButton BOT4;
    private javax.swing.JButton BOT5;
    private javax.swing.JButton BOT6;
    private javax.swing.JButton BOT7;
    private javax.swing.JButton BOT8;
    private javax.swing.JButton BOT9;
    private javax.swing.JButton C;
    private javax.swing.JButton COS;
    private javax.swing.JButton DIV;
    private javax.swing.JButton IGUAL;
    private javax.swing.JButton IVA;
    private javax.swing.JButton MULT;
    private javax.swing.JButton POTENCIA;
    private javax.swing.JButton PUNTO;
    private javax.swing.JButton RAIZ;
    private javax.swing.JButton RESTA;
    private javax.swing.JButton SEN;
    private javax.swing.JButton SUMA;
    private javax.swing.JButton TAN;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texto1;
    // End of variables declaration//GEN-END:variables
}
